### ISSUE TITLE
Issueベース開発レビュー依頼

### ISSUE THREAD

**Issue by puretipe** [puretipe/Graduation-exam#32]
Issueのレビューをお願いします。

**Comment by Tsuchiya2** [comment]
課題「issueベースの開発」のご確認をお願いいたします、（GithubProject等々が行われていないように見受けられました）

**Comment by puretipe** [comment]
失礼いたしました。
プロジェクトをprivateの状態にしてしまっておりました。publicに修正しましたので、ご確認をよろしくお願いします。

**Comment by shota-hope** [comment]
提出ありがとうございます。
概ね大丈夫そうなのですが、少し気になった点をコメントさせていただきます。

- ストーリーポイント5のissueが多く感じられました。
  - https://github.com/puretipe/Graduation-exam/issues/31
  - 上記を例にすると、例えば検索ごとにissueを分けて一つのプルリクの変更分を少なくすると変更が複雑になりにくいと思いました。
  - 全てではないですが、いくつかもう少し分割してもいいのかなと個人的に感じました。
- テーブルの設計も考えられているので、issueに〇〇モデルを作成等書くと親切かもしれません 

以上、ご確認よろしくお願いいたします。

**Comment by puretipe** [comment]
コメントありがとうございます。
ご指摘いただきました点につきまして以下のようにいたしました。

- issueを細分化し、ストーリポイント5のものが減るようにしました
- issueにモデル作成のタスクを追加しました

以上のように修正しましたので、再レビューの程よろしくお願いします。

**Comment by Tsuchiya2** [comment]
LGTMです。

**Comment by puretipe** [comment]
レビューありがとうございました。
