### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by puretipe** [puretipe/Graduation-exam#57]
## 各種情報
サービス名：VOCALOIDSelection
サービスURL：https://vocaloidselection-c60e17750340.herokuapp.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- 動画投稿・表示機能
- ユーザー登録・認証機能
- 検索機能
- 一覧表示
- 「ここが好き！」評価機能

READMEレビュー時に実装予定だった機能を実装しております。

## サービスイメージがわかるようなスクリーンショット等
現状管理画面等の通常のユーザーが使用できない機能はありません。

**Comment by busitora** [comment]
こちら、PRはどちらになりますか?

**Comment by puretipe** [comment]
プルリクエストを作成し直しましたので、再レビューをよろしくお願いいたします。
PR：https://github.com/puretipe/Graduation-exam/pull/60

**Comment by Tsuchiya2** [comment]
混乱させてしまい申し訳ございません。
卒業課題としてREADMEレビュー時のMVP機能が正しく機能しているかをチェックします。

---

上記記載のとおり、チェックを行った結果、MVP機能の確認ができました。
LGTMです１

本リリース機能の開発を引き続き進めましょう！
